services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-converter
    ports:
      - "8001:8001"
    # stdin_open: true
    tty: true
    # volumes:
    #   - .env:/.env
