package models

type ValName string

const (
	AUD ValName = "AUD"
	AZN ValName = "AZN"
	GBP ValName = "GBP"
	AMD ValName = "AMD"
	BYN ValName = "BYN"
	BGN ValName = "BGN"
	BRL ValName = "BRL"
	HUF ValName = "HUF"
	VND ValName = "VND"
	HKD ValName = "HKD"
	GEL ValName = "GEL"
	DKK ValName = "DKK"
	AED ValName = "AED"
	USD ValName = "USD"
	EUR ValName = "EUR"
	EGP ValName = "EGP"
	INR ValName = "INR"
	IDR ValName = "IDR"
	KZT ValName = "KZT"
	CAD ValName = "CAD"
	QAR ValName = "QAR"
	KGS ValName = "KGS"
	CNY ValName = "CNY"
	MDL ValName = "MDL"
	NZD ValName = "NZD"
	NOK ValName = "NOK"
	PLN ValName = "PLN"
	RON ValName = "RON"
	XDR ValName = "XDR"
	SGD ValName = "SGD"
	TJS ValName = "TJS"
	THB ValName = "THB"
	TRY ValName = "TRY"
	TMT ValName = "TMT"
	UZS ValName = "UZS"
	UAH ValName = "UAH"
	CZK ValName = "CZK"
	SEK ValName = "SEK"
	CHF ValName = "CHF"
	RSD ValName = "RSD"
	ZAR ValName = "ZAR"
	KRW ValName = "KRW"
	JPY ValName = "JPY"
)
